[package]
name = "rad-identities"
version = "0.1.0"
authors = [ "Fintan Halpenny <fintan.halpenny@gmail.com>" ]
edition = "2018"
license = "GPL-3.0-or-later"

[lib]
doctest = true
test = false

[dependencies]
anyhow = "1.0"
clap = "2.33"
either = "1.0"
lazy_static = "1"
nonempty = "0.6"
serde_json = "1.0"
structopt = "0.3"
thiserror = "1.0"
tracing = "0.1"

[dependencies.rad-clib]
path = "../rad-clib"

[dependencies.git2]
version = "=0.13.20"
default-features = false
features = []

[dependencies.libgit2-sys]
version = "0.12"
default-features = false
features = []

[dependencies.librad]
path = "../librad"

[dependencies.radicle-git-ext]
path = "../git-ext"

[dependencies.serde]
version = "1.0"
features = [ "derive" ]

[dependencies.similar]
version = "2.1"
features = [ "text" ]

[dependencies.thrussh-agent]
git = "https://github.com/erak/thrussh"
branch = "generic-agent"
default-features = false

[dependencies.url]
version = "2.1"
features = ["serde"]
